/*
 * This source file was generated by the Gradle 'init' task
 */
package org.Esercizio1;

import java.util.List;
/*Esercizio 1: Gestione Veicoli (Ereditarietà e Interfacce)
Crea un programma che gestisce una flotta di veicoli.
Definisci un'interfaccia Veicolo con metodi come avvia(), ferma(), e getTipo().
Crea una classe astratta MezzoDiTrasporto che implementa Veicolo e ha un attributo targa.
Implementa due classi concrete: Auto e Moto, ereditando da MezzoDiTrasporto.
Scrivi un programma che memorizza diversi veicoli in un array o una lista e permette di avviarli o fermarli.
 */
public class App {
   

    public static void main(String[] args) {
            List <Veicolo> veicoli = List.of(new Auto("Targa1"), new Moto("Targa2"));
            veicoli.get(0).avvia();
            veicoli.get(1).avvia();
            veicoli.get(0).ferma();
            veicoli.get(1).ferma();
            veicoli.get(0).ferma();
            System.out.println(veicoli.get(1).getTipo());
        }
}
