/*
 * This source file was generated by the Gradle 'init' task
 */
package esercizioserializzazione;
import java.io.*;
public class LetturaPoint2D{
public static void main(String[] args) throws IOException,ClassNotFoundException {
FileInputStream f =new FileInputStream("esempio.bin");
ObjectInputStream is =new ObjectInputStream(f);
Punto2D p;
p = (Punto2D)is.readObject();
is.close();
System.out.println("x,y = " +p.ascissa() + ", " + p.ordinata());
}
}
